### PR TITLE
add nfsv3-statemap.d

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
I'm not very fluent in optimizing DTrace scripts, nor NFS internals, so I apologize if there's a better way to implement this; I based this off the `vdev-statemap.d` script. I've tested this on an illumos based (DelphixOS) system, and verified it (at least) worked on my system.

**Comment by bcantrill** [comment]
Looks interesting! In this case, the entity is the host -- so there will only ever be one.  Is a statemap a useful visualization at that point, or is the intent here to merge disjoint streams from disjoint systems to create a single statemap?  Or does it make sense to make the entity be something else related to the operation (e.g., the file system)?

**Comment by prakashsurya** [comment]
> Is a statemap a useful visualization at that point, or is the intent here to merge disjoint streams from disjoint systems to create a single statemap?

I was using the output of this, along with things like the spa sync and vdev data (merging the the statemap together into a single visualization) to try and get a high level view of what the system was doing. This way, I can at least see that NFS reads/writes were being serviced at a given time, and also see the disk activity for that same timeframe.

Honestly, this hasn't been super useful yet, but I'm still learning how to gather the data I need and interpret the visualizations in a meaningful way (first time user here, and only a few hours in).

>  Or does it make sense to make the entity be something else related to the operation (e.g., the file system)?

I'll try and look into this some more. I think it might be possible to split the entity based on the particular NFS thread, which might be more interesting. IIRC, there's 1024 NFS threads by default, so we'd then get the activity based on each thread.

I think it'd also be more useful if we could show saturation (i.e. the number of IO requests being serviced), rather than simply if _any_ IO is occurring. As is, this is useful to show if NFS is idle, but doesn't help too much when there's a small amount of activity (the line is almost always non-idle, but the system is still mostly idle, since it's a small amount of NFS activity on a server with lots of resources).

It might be worth closing this until I can investigate these improvements.

**Comment by prakashsurya** [comment]
Here's an example; from top to bottom, that's cpu, nfsv3, spa-sync, and vdev data. It's interesting that NFS was active towards the end of the sample, but that activity didn't really result in the disks being utilized (at least, this is my interpretation).

statemap

**Pull request closed without merging**
