### PR TITLE
Improve option and argument parsing with structopt

### PR DESCRIPTION
**Pull request by djc**
This builds on @masklinn's work in #35.

### CODE REVIEW

**Comment by djc** [comment]
The help message is auto-generated:

```
djc@djc-mbp statemap $ cargo run -- -h
   Compiling statemap v0.1.0 (file:///Users/djc/src/statemap)                                       
    Finished dev [unoptimized + debuginfo] target(s) in 2.90s
     Running `target/debug/statemap -h`
statemap 0.1.0
Bryan Cantrill <bryan@joyent.com>

USAGE:
    statemap [OPTIONS] <file>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -b <begin>           time offset at which to begin statemap
    -c <coalesce>        coalesce target
    -d <duration>        time duration of statemap
    -e <end>             time offset at which to end statemap
    -s <sortby>          state to sort by (defaults to entity name)

ARGS:
    <file> 
```

Since this is a refactoring that does not add functionality, I've also not added any tests (but I've checked that the existing tests pass). I actually don't have experience in general with testing command-line interfaces in Rust, though I know at least cargo has them.

The problem this is solving is the relative verbosity of writing code to parse command-line options. The structopt approach takes ~70 fewer lines of code, eliminating the need for some code that I would qualify as boilerplate. I find the resulting code easier to follow (although it also makes some things less explicit).

**Comment by bcantrill** [comment]
So, I think this might be a matter of personal taste.  I should have actually applied your diff and run it, seen that it does in fact have a help message, and then I would have presumably realized that structopt was using the doc comment to generate this.  But that it wasn't obvious by looking at it is part of my issue:  I'm not so into having the doc comment be load bearing with respect to the help message.  I understand that others might differ on this, but on this issue, I prefer being more explicit.  (Indeed, even get getopt crate is still a tad too framework-y for my taste.)  Is there a strong sense in the Rust community of how this should be done?  Because unless the way it's currently being done is thought of as completely non-idiomatic, I'm inclined to leave it...

**Comment by djc** [comment]
I definitely understand that there's a tradeoff. I do think structopt is closer to the direction of Rust idiom in this space. For some background, these are recent download numbers from the 4 most popular options for this in the [Command-line interface](https://crates.io/categories/command-line-interface) category on crates.io:

- [clap](https://clap.rs/): 510k
- [getopts](https://github.com/rust-lang/getopts): 240k
- [docopt](https://github.com/docopt/docopt.rs): 120k
- [structopt](https://github.com/TeXitoi/structopt): 60k

Still, I believe all the momentum points towards more type-decorated declarative definitions (getopts download counts are going down, structopt counts are going up). I believe the next version of Clap will also come with a custom derive mode (which is mentioned in the Rust CLI working group book [here](https://github.com/rust-lang-nursery/cli-wg/blob/master/src/tutorial/cli-args.md)).

**Comment by killercup** [comment]
Hey, just wanted to chime in here 'caus this is one of the topics the CLI WG is concerning itself with :)

> I'm not so into having the doc comment be load bearing

You can alternatively use something like `#[structopt(short = "o", help = "output file")]`.

> Indeed, even get getopt crate is still a tad too framework-y for my taste.

Heh, yeah, coming from other langs with loads of built-in tooling (that includes shell scripts in this case!), I can see what you mean!

I wouldn't call getopt un-idiomatic per-se. It solves a problem in a nice, minimalistic way. I personally consider structopt to be the most idiomatic way to deal with CLI arguments in Rust right now, though: You define a well-typed structure you expect and the boilerplate of parsing the raw args vector is generated for you. It works very well with complex types, supports enums to describe subcommands, and also allows to "flatly" embed other types that implement the Structopt trait.

All this is also possible by using clap directly (structopt is a macro that basically generates clap-based code; the next clap version will include it). Clap is probably the most featureful CLI arg parsing library we currently have, with nice error messages, great suppot for dealing with subcommands, and goodies like generating shell completitions (and soon also generating man pages).

Obviously, all that comes with tradoffs: It's less obvious what's going on (the usual trade-off with most abstraction), and with a bunch of new dependencies your program will take longer to compile as well as increase in binary size.

**Comment by djc** [comment]
Let's just close this then.

**Pull request closed without merging**
